### ISSUE TITLE
Auto Sync not working with Anki upgrade version 23.10.1

### ISSUE THREAD

**Issue by xy3xx** [Robin-Haupt-1/Auto-Sync-Anki-Addon#11]
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-19 11:47:02

When loading Auto Sync:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\501542723\__init__.py", line 1, in <module>
    from . import  main
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\501542723\main.py", line 3, in <module>
    from .config import AutoSyncConfigManager
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\501542723\config.py", line 2, in <module>
    from .constants import AUTO_SYNC_CONFIG_NAME, CONFIG_DEFAULT_CONFIG
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\501542723\constants.py", line 14, in <module>
    AUTO_SYNC_ICON = QApplication.instance().style().standardIcon(QStyle.SP_BrowserReload)
AttributeError: type object 'QStyle' has no attribute 'SP_BrowserReload'

**Comment by Robin-Haupt-1** [comment]
I have released an update that fixes this bug

**Comment by xy3xx** [comment]
Wow, that was fast. Thank you!
